config/routes.rb
Rails.application.routes.draw do
  root "findings#index"
  resources :findings, only: [:index, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  get "test", to: redirect("/test.html")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/extractor.rb
# uses LLM to extract all the bits relevant to the keywords into a single document.
# Could also be a "summarizer".

# that worked:
# find all datapoints that mention API or automation as a standalone word in the context of
# [INSERT YOUR TOPIC HERE; web or rest apis; ruby design patterns; etc.] and extract the data
# relevant to that data point. if present it should contain
# description, author, and a link for further reading. look through the whole document and all
# sections to find any mentions of the above mentioned keywords:
# ...html...
class Extractor
end

app/models/finder.rb
# This class' name could also be Sloth.
class Finder
  attr_writer :keywords, :first, :last

  def find_matches
    ScraperLogger.logger.info "🔎 Searching for keywords: #{@keywords.join(", ")}"

    scope = ScrapedPage.all
    scope = scope.first(@first) if @first
    scope = scope.last(@last) if @last

    results = []
    scope.each do |page|
      result = page.keyword_mentions(keywords: @keywords)
      if result
        result[:url] = page.url
        results << result
      end
    end

    ScraperLogger.logger.info "Found #{results.size} matches 🔍"

    results.reverse
  end

  # This is useful when you run things locally.
  def find_and_log
    ScraperLogger.logger.info "Searching for keywords"

    scope = ScrapedPage.all
    scope = scope.first(@first) if @first
    scope = scope.last(@last) if @last

    scope.each do |page|
      result = page.keyword_mentions(keywords: @keywords)
      if result
        ScraperLogger.logger.info "✅ HIT #{page.url}"
        ScraperLogger.logger.info result[:related_texts]
        ScraperLogger.logger.info "\n"
      else
        ScraperLogger.logger.info "❌ MISS #{page.url}"
      end

      ScraperLogger.logger.info "-" * 60
    end

    nil
  end

  private

  # keywords - Array of keywords to search for, e.g.:
  #   ["api", "openapi", "automation", "rest", "graphql", "rpc", "soap", "webhook", "scrap", "event-driven", "serializ"]
  # first - Integer, the number of pages to search through
  # last - Integer, the number of pages to search through
  def initialize(keywords:, first: nil, last: nil)
    ScraperLogger.logger.info "Initialize logger for keywords: #{keywords.join(", ")}"

    @keywords = keywords
    @first = first
    @last = last
  end
end

app/models/scraped_page.rb
class ScrapedPage < ApplicationRecord
  validates :url, presence: true, uniqueness: true

  def keyword_mentions(keywords: [])
    return nil if keywords.empty?

    regex = /\b(#{keywords.join("|")})\b/i
    doc = Nokogiri::HTML(body)
    texts = doc.xpath("//p | //a | //div[not(child::*)]").map(&:text).map(&:strip).uniq

    matches = texts.select { |text| text.match?(regex) }

    if matches.any?
      related_texts = matches.reverse.join("\n\n")
      {related_texts: related_texts}
    end
  end
end

app/models/simple_scraper.rb
require "httparty"
require "nokogiri"

class SimpleScraper
  def initialize(base_url, from: 1, to: 10)
    @base_url = base_url
    @from = from
    @to = to

    puts "Crawler initialized"
  end

  def crawl
    puts "Start crawling"

    current_page = @from
    consecutive_404s = 0

    while @to.nil? || current_page <= @to
      puts "Crawling page #{current_page}"

      url = "#{@base_url}/#{current_page}"
      response = HTTParty.get(url)

      if response.code == 404
        consecutive_404s += 1
        break if consecutive_404s >= 3
      else
        consecutive_404s = 0
        scrape(response.body, url)
      end

      current_page += 1
      sleep 1
    end

    puts "Crawling finished with #{ScrapedPage.count} pages now available"
  end

  def scrape(page_content, url)
    # Parse the HTML and extract the <body> element including the tag
    parsed_page = Nokogiri::HTML(page_content)
    body_content = parsed_page.at("body").to_html

    # Find or initialize the ScrapedPage record and update the body
    scraped_page = ScrapedPage.find_or_initialize_by(url: url)
    scraped_page.body = body_content
    scraped_page.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/findings_controller.rb
class FindingsController < ApplicationController
  def index
  end

  def create
    keywords = sanitize_keywords(findings_params[:keywords])

    # We don't store findings yet so just logging for fun and insights:
    logger.info("SESSION #{session.id} searched for #{keywords}")

    if keywords.empty?
      Sentry::Metrics.increment("something_found")

      flash.now.alert = "Please enter at least one keyword."
      render :index, status: :unprocessable_entity
    else
      Sentry::Metrics.increment("nothing_found")

      finder = Finder.new(keywords: keywords)
      @results = finder.find_matches
      @results.reverse

      respond_to do |format|
        format.turbo_stream
      end
    end
  end

  private

  def findings_params
    params.require(:findings).permit(:keywords)
  end

  def sanitize_keywords(keywords)
    keywords.split(",").map { |keyword| ActionController::Base.helpers.sanitize(keyword.strip) }.reject(&:blank?)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def search
    keywords = params[:keywords].split(",").map(&:strip)
    finder = Finder.new(keywords: keywords)
    @results = finder.find_matches

    respond_to do |format|
      format.turbo_stream
      format.html {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sloth_facts_helper.rb
module SlothFactsHelper
  def sloth_facts
    [
      "🦥 My results are stellar. What are yours?",
      "🦥 No worries, sloths are the only thing that matters.",
      "🦥 I'm urgently chilled. You seem not.",
      "🦥 You seem heated. I'm cool. Like 30-34 degrees Celsius cool.",
      "🦥 Sloth out bro; and try some good keywords.",
      "🦥 I'm not sure what you're looking for. But I'm sure you're not looking for me.",
      "🦥 Slothing is the new black.",
      "🦥 Not today, not today, not today...",
      "🦥 Maybe tomorrow...",
      "🦥 Sloths have a mutualistic ectosymbiotic relationship with the flora and fauna growing on their backs, consisting of fungi, algae, and moths.",
      "🦥 Sloths are two- or three-toed. To look better, they have four toes in Zootopia DALL-E style.",
      "🦥 I go 240 metres per hour. You just sit.",
      "🦥 I'm a vegan, preferring to eat leaves and sometimes fruit, insects, lizards, and bird's eggs. Nothing too fancy."
    ]
  end
end

app/views/findings/_results.html.erb
<% if results.present? %>
  <% results.each do |result| %>
    <div class="result-card">
      <p><%= result[:related_texts].gsub(/\n\n/, "<br/><br/>").html_safe %></p>
      <p><%= link_to result[:url], result[:url], target: "_blank" %></p>
    </div>
  <% end %>
  <div>
    <p class="sloth-fact">🦥 Seek the truth and ye shall find</p>
  </div>
<% else %>
  <p class="sloth-fact"><%= sloth_facts.sample %></p>
<% end %>

app/views/findings/create.turbo_stream.erb
<%= turbo_stream.replace "results" do %>
  <div id="results">
    <h1><%= "#{@results.count} findings..." %></h1>
    <%= render "results", results: @results || [] %>
  </div>
<% end %>

app/views/findings/index.html.erb
<h1>Sloth Finder - Ruby Weekly edition</h1>

<img src="<%= asset_path("rich-sloth.png") %>" alt="Rich Sloth" class="rich-sloth-image">

<p>
  Sloth Finder helps you encounter the most amazing Ruby articles around your favorite
  Ruby and Rails topics for the past decade. This tool was made because the creator, a Sloth in human form, was
  interested in all the best articles around his favorite weird Ruby niche, so he built a primitive
  search and looked for:
</p>

<code>
api, openapi, automation, rest, graphql, rpc, soap, webhook, scrap, event-driven, serializ
</code>

<p>
  What followed was a wealth of articles full of knowledge, understanding of his niche, and
  potential for connecting to potential leads and partners. Instead of calling it a day, he
  decided to share the tool and some extra knowledge around it with the community.
</p>

<h2>But I have no niche.</h2>

<p>
  If you are a "regular" Ruby or Ruby dev who doesn't care about anything else than
  vanilla, there must be things that still interest you. Here's some
  inspiration:
</p>

<code>
  ruby 4
  rails 8
  sinatra
  hotwire
  phlex
  enumerable
  rbs
  easter egg
  ractors
  postgres
  sqlite
  deploy
  kamal
  danger on rails
  sidekiq
  solid queue
  beer
  ...
</code>

<h2>What makes it Sloth?</h2>

<ul>
  <li class="emoji-sloth">Minimal effort development for max benefit.</li>
  <li class="emoji-search">It's the laziest search ever invented: We are looking for case insensitive words with open ends; e.g. "api" will match "API", "APIs", "apimatic". It goes back to issue 201 in 2014. Let me know if you want the earlier ones and we'll ask Peter Cooper if we can scrape some of the old XML archives.</li>
  <li class="emoji-slow">It's slow: Loading times have been spotted to be around 1-2 seconds on local and more in prod. Chill is king; good things take time.</li>
  <li class="emoji-rails">Written with the laziest tech stack ever imagined, the one-sloth-framework: Rails on SQlite deployed on Render ($7.25 server costs, <a href="https://buymeacoffee.com/richstoneio" target="_blank">consider buying a banana for Sloth if you got any value from the tool</a>). We'll move this to Rails 8 and Kamal 2 on a proper server once the future is here.</li>
  <li class="emoji-claude">Frontend "design" outsourced to Claude Opus.</li>
  <li class="emoji-tests">Obviously, no one wrote tests for this simple MVP (the Sloth promised adding some, if we go past MVP and add more features).</li>
</ul>

<%= form_with url: findings_path, method: :post do |form| %>
  <%= form.label :keywords, class: "keywords-label" %>
  <%= form.text_field "findings[keywords]", placeholder: "comma-separated keywords or phrases" %>
  <%= form.submit "Find 🦥" %>
<% end %>

<div id="results">
    <%# Necessary to display the flash alert in the turbo stream, otherwise it's %>
    <%# hard to make it to behave properly (e.g., does not disappear when search is triggered). %>
    <%# Leads to poor UX, where the alert is shown instead of the previous results. %>
    <% if flash.alert %>
      <div class="alert alert-danger">
        <%= flash.alert %>
      </div>
    <% end %>
  <%= render "results", results: @results || [] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleScraperApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">

    <!-- SEO Meta Tags -->
    <meta property="og:title" content="Search Ruby Weekly articles like a Sloth">
    <meta property="og:description" content="The search for the Ruby Weekly newsletter.">
    <meta property="og:image" content="<%= asset_path("rich-sloth.png") %>">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Search Ruby Weekly articles like a Sloth">
    <meta name="twitter:description" content="The search for the Ruby Weekly newsletter.">
    <meta name="twitter:image" content="<%= asset_path("rich-sloth.png") %>">
  </head>

  <body>
    <%= yield %>
  </body>

  <footer>
      Made with 🍌 in Barcelona's <a href="https://www.apishop.io" target="_blank">apishop.io</a> 🔌
      | Open sauced on <a href="https://github.com/RichStone/sloth-finder" target="_blank">github</a>
  </footer>
</html>

app/views/search/_results.html.erb
<% if results.present? %>
  <h2>Search Results</h2>
  <% results.each do |result| %>
    <div>
      <p><%= result[:related_texts] %></p>
    </div>
  <% end %>
<% else %>
  <p>No results yet.</p>
<% end %>